name: Build

on:
  push:
    paths:
    - .github/workflows/build.yml
    - Libraries/**
    - Source/**
    - Unity/**

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up environment
      run: ${{ github.workspace }}\.github\workflows\set_up_env.ps1 "${{ github.workspace }}\Source\CustomAvatar\manifest.json"

    - name: Fetch Beat Saber Bindings
      run: git clone https://${{ github.actor }}:${{ secrets.PRIVATE_GITHUB_TOKEN }}@github.com/nicoco007/BeatSaberBindings --branch v${{ env.GAME_VERSION }} --single-branch '${{ runner.temp }}\BeatSaberBindings\Beat Saber_Data\Managed'

    - name: Download dependencies
      uses: nicoco007/download-beatmods-deps@main
      with:
        manifest: ${{ github.workspace }}\Source\CustomAvatar\manifest.json
        path: ${{ runner.temp }}\BeatSaberBindings
        additional-dependencies: '{ "Unity.XR.Hands": "^1.1.0" }'

    - name: Add NuGet source
      run: dotnet nuget update source "nicoco007 GitHub Packages" --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
  
    - name: Build Debug
      run: dotnet build Source\CustomAvatar\CustomAvatar.csproj -c Debug -p:BeatSaberDir=${{ runner.temp }}\BeatSaberBindings

    - name: Upload Debug
      uses: actions/upload-artifact@v3
      with:
        name: BeatSaberCustomAvatars-${{ env.ZIP_VERSION }}-DEBUG
        path: Source\CustomAvatar\bin\Debug\net472\publish

    - name: Build Release
      run: dotnet build Source\CustomAvatar\CustomAvatar.csproj -c Release -p:BeatSaberDir=${{ runner.temp }}\BeatSaberBindings

    - name: Upload Release
      uses: actions/upload-artifact@v3
      with:
        name: BeatSaberCustomAvatars-${{ env.ZIP_VERSION }}-RELEASE
        path: Source\CustomAvatar\bin\Release\net472\publish

    - name: Build Editor
      run: dotnet build Source\CustomAvatar-Editor\CustomAvatar-Editor.csproj -c Release -p:BeatSaberDir=${{ runner.temp }}\BeatSaberBindings

    - name: Upload Editor
      uses: actions/upload-artifact@v3
      with:
        name: BeatSaberCustomAvatars-${{ env.ZIP_VERSION }}-Editor
        path: Source\CustomAvatar-Editor\bin\Release\net472\publish\CustomAvatar.dll
    
    - name: Upload Unity Project
      uses: actions/upload-artifact@v3
      with:
        name: BeatSaberCustomAvatars-${{ env.ZIP_VERSION }}-UnityProject
        path: Unity
